# 基本配置
baseurl: https://git-mengfan.github.io/
url: https://git-mengfan.github.io/
date_format: "ordinal"
title: Mf是个大坏蛋
subtitle: "从来如此，便对吗？"
description: "Mf是个大坏蛋的个人主页"
keywords: Mf,
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
components:
  # 不蒜子访问统计
  busuanzi:
    enabled: true
    start_date: 2020-11-08
# 作者相关
author: Fan Meng
organization:
organization_url:
github_username: git-mengfan
location: Beijing, China
email: meng_fan_@outlook.com

# 导航栏
navs:
  - href: /
    label: 首页

  - href: /categories/
    label: 分类

  - href: /about/
    label: 关于

# Jekyll配置
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

repository: git-mengfan/git-mengfan.github.io

# 评论相关
comments_provider: gitalk
gitalk:
  owner: git-mengfan
  repo: blog-comments
  clientID: f14a67d33ff4694206dd
  clientSecret: 41ffbb37e4d87e68c7f76ef450511aec1ca672af
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: false

# 搜索
simple_jekyll_search:
  # 是否支持全文搜索
  fulltext: false
  # 最多显示多少条搜索结果
  limit: 10
